### ISSUE TITLE
Issues with collapsed code and page scrollbars

### ISSUE THREAD

**Issue by herronelou** [Automattic/syntaxhighlighter#107] opened 2019-05-06 04:47 UTC
Hi,
There seems to be a clash between my theme and the syntax highlighter.
When expanding a collapsed code block, the browser doesn't seem to understand that the size of the page has changed, and the vertical scroll bar for the page doesn't allow to scroll far enough.

Theme used: Avada

Not sure if this is a theme issue or plugin issue.
Thanks

**Comment by alexsanford** [comment] 2020-03-12 19:28
I am unable to reproduce this. When I expand a collapsed code block on Avada 5.2, WordPress 5.3.2 it does not have any trouble.

Closing this for now. If the problem persist, please ask in the [Support Forums](https://wordpress.org/support/plugin/syntaxhighlighter/), and provide as much information as you can regarding how to reproduce the issue.

**Closed as completed by alexsanford** 2020-03-12 19:28 UTC
