### ISSUE TITLE
'&' and '>' are still displayed incorrectly.

### ISSUE THREAD

**Issue by dmitriano** [Automattic/syntaxhighlighter#115] opened 2019-11-07 18:07 UTC
In version 3.5.1 the author added a code that replaces ‘<‘:

`$code = str_replace( '&lt;', '<', $code );`

but it is not enough, because there is ‘&’ and ‘>’ in C++ code.

See [my fix](https://developernote.com/2019/05/making-syntaxhighlighter-plugin-display-symbol-correctly/) and an example of a [page with C++ code](https://developernote.com/2019/08/parsing-guid-in-c-with-a-regular-expression/).

**Comment by alexsanford** [comment] 2020-03-12 19:41
Are you using the block editor or the classic editor? If the classic editor, are you using the "Visual" or "Text" tab?

If you are using the "Visual" tab on the classic editor, then this is a duplicate of https://github.com/Automattic/syntaxhighlighter/issues/65. Otherwise, please give provide some more information on how to reproduce the issue.

**Comment by alexsanford** [comment] 2020-05-13 17:08
Closing due to inactivity.

**Closed as completed by alexsanford** 2020-05-13 17:08 UTC
Labels: [Status] Needs Author Reply
