### ISSUE TITLE
Feature Request: Add `swift` as a language preference

### ISSUE THREAD

**Issue by andreabadgley** [Automattic/syntaxhighlighter#124] opened 2020-03-09 22:09 UTC
I chatted with a customer today who asked that I put in a feature request for the Syntax Highlighter Code Block, so here I am :)

> although it's reasonably common to have "swift" as a language preference for the syntax highlighters these days - there's nothing in the wordpress system that does "the right thing" here. I'm using Objective-C as a workaround, but it would be nice to explicitly have 'swift' for the SyntaxHighlightedCode block option.

chat: 8306955-hc
followup ticket if request is fulfilled: 2777928-zen

**Comment by alexsanford** [comment] 2020-03-13 19:03
Thanks @andreabadgley! Looks like this is a duplicate of https://github.com/Automattic/syntaxhighlighter/issues/38. Closing this one for now 🙂

**Closed as completed by alexsanford** 2020-03-13 19:03 UTC
Labels: [Type] Enhancement
