### ISSUE TITLE
Right angle brackets ('>') get transformed into html entities ('&gt;')

### ISSUE THREAD

**Issue by haster** [Automattic/syntaxhighlighter#108] opened 2019-05-07 08:16 UTC
(Note: I realise that @Viper007Bond has unfortunately passed away. I register this issue here in the hope that someone will take over and look into this and in the hope I can help someone else with the workaround I found.)

WordPress: 5.1.1
SyntaxHighlighter-Evolved: 3.5.0

When I insert SyntaxHighlighter code blocks containing right angle brackets (for instance, xml) and preview /publish the page using a user with role "Author" or below those brackets get tranformed into their HTML-entities and this breaks the syntax highlighting.

For instance, this code:
![screenshot_wp_syntaxhiglight_code](https://user-images.githubusercontent.com/1228217/57284039-b2554b00-70b0-11e9-83bf-d41ade47df49.png)

gets published as this:
![screenshot_wp_syntaxhiglight_wrong](https://user-images.githubusercontent.com/1228217/57284062-c13bfd80-70b0-11e9-8d56-0fe4d2e7401d.png)

Workaround: if I preview/publish using an account with role "Editor" or "Admin" everything works as expected and I get:
![screenshot_wp_syntaxhiglight_right](https://user-images.githubusercontent.com/1228217/57284207-fd6f5e00-70b0-11e9-85d4-b66884977ed8.png)

**Comment by DannyCooper** [comment] 2019-05-14 12:06
Hi @haster,

Another workaround I found was to add this code to line 518 of `syntaxhighlighter.php`.

`$code = htmlspecialchars_decode( $code );`

Note: this is one possible workaround, I take no responsibility for your implementation.

**Comment by alexsanford** [comment] 2020-03-12 19:36
I'm quite certain that I've also seen this, but when I try to reproduce now it doesn't seem to happen. Could you please confirm whether this is still happening for you on the latest version of this plugin?

**Comment by lancewillett** [comment] 2020-04-27 23:33
Closing due to lack of new reports. Please re-open if you can reproduce with latest version of the plugin.

**Closed as completed by lancewillett** 2020-04-27 23:33 UTC
Labels: [Type] Bug, [Status] Needs Author Reply

**Comment by adnanafzal565** [comment] 2020-07-02 04:43
@DannyCooper your workaround really fixes the issue. But I am afraid after the next update, we have to do that again.
It would be better if the plugin author could do that.

**Comment by Marcussacapuces91** [comment] 2020-07-05 09:19
Hi, of course, it did it again as it wasn't corrected.
Please, change line 531 of syntaxhighlighter.php to 

`$code = htmlspecialchars_decode( $code );`

**Comment by alexsanford** [comment] 2020-07-07 19:43
I tried to reproduce this again, and I am unable to do so. I created a post and added the XML code above. I tried it both using the block editor and the "SyntaxHighlighter Code" block, as well as in the classic editor using the `[xml]` shortcode. I opened the page on the frontend both logged in, and not logged in. In all cases, I do not see the `&gt;` code on the frontend.

@adnanafzal565 and/or @Marcussacapuces91 are you able to give me some information on your setup that would help me to reproduce the bug? For example, the block/shortcode settings, the overall SyntaxHighlighter settings, and anything else that might be contributing to this?

I'm happy to reopen this bug and add it to our queue, but I need to be able to reproduce it first so we can adequately evaluate and test the solution.

**Comment by svillar** [comment] 2020-09-30 14:46
I'm getting this with pure HTML code. For example with this piece of code:
```
<div style="display: flex; flex-wrap: wrap; align-content: flex-end; width: 425px; height: 70px; border: 2px solid black">
  <div style="height: 20px">This text should be at the bottom of its container</div>
</div>
```
Remember to select HTML/XHTML... in the code language combo

**Comment by adnanafzal565** [comment] 2020-10-01 17:04
Thanks.

**Comment by svillar** [comment] 2020-10-01 17:09
> Thanks.

BTW I found out that everything works fine *if* I use escaped HTML, then the plugin correctly unescapes it.

**Comment by anatomystuff** [comment] 2021-01-02 16:17
> Hi, of course, it did it again as it wasn't corrected.
> Please, change line 531 of syntaxhighlighter.php to
> 
> `$code = htmlspecialchars_decode( $code );`

To clarify I found this function in syntaxhighlighter.php
`function shortcode_hack( $content, $callback, $ignore_html = true ) {`
change
`return $content;`
to
`return htmlspecialchars_decode($content);`

Worked OK for me but depends if on every plugin update it get's invalidated again.

**Comment by kashifb007** [comment] 2021-01-02 16:20
> Hi, of course, it did it again as it wasn't corrected.
> Please, change line 531 of syntaxhighlighter.php to
> 
> `$code = htmlspecialchars_decode( $code );`

To clarify I found this function in syntaxhighlighter.php
`function shortcode_hack( $content, $callback, $ignore_html = true ) {`
change
`return $content;`
to
`return htmlspecialchars_decode($content);`

Worked OK for me but depends if on every plugin update it get's invalidated again

**Comment by kashifb007** [comment] 2021-01-02 16:23
> I tried to reproduce this again, and I am unable to do so. I created a post and added the XML code above. I tried it both using the block editor and the "SyntaxHighlighter Code" block, as well as in the classic editor using the `[xml]` shortcode. I opened the page on the frontend both logged in, and not logged in. In all cases, I do not see the `&gt;` code on the frontend.
> 
> @adnanafzal565 and/or @Marcussacapuces91 are you able to give me some information on your setup that would help me to reproduce the bug? For example, the block/shortcode settings, the overall SyntaxHighlighter settings, and anything else that might be contributing to this?
> 
> I'm happy to reopen this bug and add it to our queue, but I need to be able to reproduce it first so we can adequately evaluate and test the solution.

My issue is simply on SyntaxHighlighter Evolved v 3.4.1
Any time of entering angle brackets < > it spits out HTML code as below
![image](https://user-images.githubusercontent.com/16262133/103461485-afdc4600-4d16-11eb-9731-384501fa7c75.png)
`htmlspecialchars_decode()`
is the fix
![image](https://user-images.githubusercontent.com/16262133/103461504-c5517000-4d16-11eb-94e6-0808dcab0ccd.png)

**Comment by bikeactuary** [comment] 2021-01-30 23:53
> > Please, change line 531 of syntaxhighlighter.php to
> > `$code = htmlspecialchars_decode( $code );`
> 
> @alexsanford
> 
> To clarify I found this function in syntaxhighlighter.php
> `function shortcode_hack( $content, $callback, $ignore_html = true ) {`
> change
> `return $content;`
> to
> `return htmlspecialchars_decode($content);`

Line 663 (replacing with `return htmlspecialchars_decode($content)`) is what fixed it for me as of latest version. Line 531 had no effect.
